version: '3.8'
services:
  pocketbase:
    pull_policy: if_not_present
    image: whyisybaactaken/pocketbase:latest
    entrypoint: ["pocketbase","serve","--dir","/data","--http","0.0.0.0:8080"]
    volumes:
      - ./data:/data
